// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package provider

import (
	"github.com/xh-polaris/meowcloud-content/biz/adaptor"
	"github.com/xh-polaris/meowcloud-content/biz/application/service"
	"github.com/xh-polaris/meowcloud-content/biz/infrastructure/config"
	"github.com/xh-polaris/meowcloud-content/biz/infrastructure/mapper/user"
)

// Injectors from wire.go:

func NewUserServerImpl() (*adaptor.UserServerImpl, error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, err
	}
	userIMongoMapper := user.NewMongoMapper(configConfig)
	userServiceImpl := &service.UserServiceImpl{
		Config:          configConfig,
		UserMongoMapper: userIMongoMapper,
	}
	userServerImpl := &adaptor.UserServerImpl{
		Config:      configConfig,
		UserService: userServiceImpl,
	}
	return userServerImpl, nil
}
